name: Simple Deploy

on:
  push:
    branches: ['main'] # ganti jika perlu
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }} # contoh: 128.199.xx.xx
          username: ${{ secrets.SSH_USER }} # contoh: root
          key: ${{ secrets.SSH_KEY }} # isi private key
          port: ${{ secrets.SSH_PORT }} # opsional, default 22
          script: |
            cd /root/project/rentverse-backend
            git pull
            npm i --omit=dev
            pm2 restart rentverse-backend
